Fixed compile error
src/components/NewProjectModal.tsx:92:16 - error TS2741: Property 'children' is missing in type '{ title: string; }' but required in type 'SectionProps'.

92               <Section title="Examples">
                  ~~~~~~~

  ../../.yarn/__virtual__/@atlaskit-side-navigation-virtual-b748a36dd4/0/cache/@atlaskit-side-navigation-npm-3.4.2-6314e3567b-6e27421786.zip/node_modules/@atlaskit/side-navigation/dist/types/components/Section/section.d.ts:7:5
    7     children: React.ReactNode;
          ~~~~~~~~
    'children' is declared here.